### ISSUE TITLE
Specifically looking for Java in java_vm

### ISSUE THREAD

**Issue by ghost** [lucasluqui/spiralview#1]
For Spiral Knights Windows build the Java is placed in **java_vm** directory, but on Linux it's just **java** (either as actual Java folder or symbolic link to it). Not sure about the macOS, though.
It would be nice if SpiralView would also look for Java from this dir.
Also, I use opportunity to thank you for developing this useful tool! I find the Level Editor and Interface Tester the most useful as I've needed these two functionalities for some time now.

**Comment by lucasluqui** [comment]
Thanks for reporting, addressed on the latest commit!
https://github.com/lucas-allegri/spiralview/commit/8392346931b61d295c83d255df075b48b26133a6
